# Lab Assignment 2: How to Load CSV, ASCII, and other data into Python
## DS 6001

100 points

### Instructions
Please answer the following questions as completely as possible using text, code, and the results of code as needed. Format your answers in a Jupyter notebook. To receive full credit, make sure you address every part of the problem, and make sure your document is formatted in a clean and professional way.

## Problem 1

There are several data files attached to this lab assignment, with different extensions. First, download all of these data files, and save them in the same folder on your local machine. Your task in the following questions is to load each file into Python correctly, so that you can begin the process of data cleaning. If the variable names are included in the file, use those names to name the columns. If the variable names are not included, use these names in order:

In [11]:
column_names = ["Country", "Happiness score", "Whisker-high", "Whisker-low", 
  "Dystopia (1.92) + residual", "Explained by: GDP per capita", 
  "Explained by: Social support", "Explained by: Healthy life expectancy", 
  "Explained by: Freedom to make life choices", "Explained by: Generosity", 
  "Explained by: Perceptions of corruption" ]

### Part a
Import the packages you will need. Then write code to change the working directory to the folder in which you saved the data files, run the code displayed above to create the `column_names` list, load `data_clean.csv`, and display the output of the `.info()` method of `data_clean`. [4 points]

In [65]:
import pandas as pd
import numpy as np
import os

os.chdir(os.path.dirname(os.path.abspath('labassignment2.ipynb')))
print(os.getcwd())

data_clean = pd.read_csv("data_clean.csv", names=column_names, header=0)
data_clean.head(3).T

c:\Users\tjroc\Documents\DATA_SCIENCE\DataPipelineArchitecture\DPALab2_TJ\DPALab2_TJ\lab data\lab data

                                                  0       1        2
Country                                     Finland  Norway  Denmark
Happiness score                               7.632   7.594    7.555
Whisker-high                                  7.695   7.657    7.623
Whisker-low                                   7.569    7.53    7.487
Dystopia (1.92) + residual                    2.595   2.383     2.37
Explained by: GDP per capita                  1.305   1.456    1.351
Explained by: Social support                  1.592   1.582     1.59
Explained by: Healthy life expectancy         0.874   0.861    0.868
Explained by: Freedom to make life choices    0.681   0.686    0.683
Explained by: Generosity                      0.192   0.286    0.284
Explained by: Perceptions of corruption       0.393    0.34    0.408

In [66]:
print(data_clean.info())

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     156 non-null    str
 1   Happiness score                             156 non-null    float64
 2   Whisker-high                                156 non-null    float64
 3   Whisker-low                                 156 non-null    float64
 4   Dystopia (1.92) + residual                  156 non-null    float64
 5   Explained by: GDP per capita                156 non-null    float64
 6   Explained by: Social support                156 non-null    float64
 7   Explained by: Healthy life expectancy       156 non-null    float64
 8   Explained by: Freedom to make life choices  156 non-null    float64
 9   Explained by: Generosity                    156 non-null    float64
 10  Explained by: Perceptions of corruption     156 non-null    float64
dtypes: float64(10), str(1)
memory usage: 13.5 KB
None

### Part b
Load `data1.csv`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

**I decided to add skiprows=2 because when I viewed the first 3 rows I saw that in the original file there are two rows used for a title and url rather than any data information. I used the docstring to identify which variable I needed to specify to skip those rows.**

In [20]:
data1 = pd.read_csv('data1.csv',skiprows=2)
data1.head(3).T

                                                  0       1        2
Country                                     Finland  Norway  Denmark
Happiness score                               7.632   7.594    7.555
Whisker-high                                  7.695   7.657    7.623
Whisker-low                                   7.569    7.53    7.487
Dystopia (1.92) + residual                    2.595   2.383     2.37
Explained by: GDP per capita                  1.305   1.456    1.351
Explained by: Social support                  1.592   1.582     1.59
Explained by: Healthy life expectancy         0.874   0.861    0.868
Explained by: Freedom to make life choices    0.681   0.686    0.683
Explained by: Generosity                      0.192   0.286    0.284
Explained by: Perceptions of corruption       0.393    0.34    0.408

### Part c
Load `data2.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [6 points]

**I loaded the data and saw that this time there was an additional row with a comment that was not data - however it came after the column names. I used the previous column name vector and simply skipped the first 4 rows of data (leaving me with only data values, no headers). Alternatively, I could have skipped the first two rows like I did in part b, and then updated data2 with .drop(0) to drop the row with the comment.**

In [40]:
data2 = pd.read_csv('data2.txt', skiprows = 4, header = None,names = column_names)
#You could also do this:
#data2 = pd.read_csv('data2.txt', skiprows = 2)
#data2 = data2.drop(0) 
data2.head(3).T

                                                  0       1        2
Country                                     Finland  Norway  Denmark
Happiness score                               7.632   7.594    7.555
Whisker-high                                  7.695   7.657    7.623
Whisker-low                                   7.569    7.53    7.487
Dystopia (1.92) + residual                    2.595   2.383     2.37
Explained by: GDP per capita                  1.305   1.456    1.351
Explained by: Social support                  1.592   1.582     1.59
Explained by: Healthy life expectancy         0.874   0.861    0.868
Explained by: Freedom to make life choices    0.681   0.686    0.683
Explained by: Generosity                      0.192   0.286    0.284
Explained by: Perceptions of corruption       0.393    0.34    0.408

### Part d
Load `data3.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

**I saw that between each column name was the characters "\t", and that there were two rows which contained miscellanious information. So I decided to skip the first two rows, and set the delimiter using sep = r'\t' (it has to be a raw string be \t is an escape character).**

In [49]:
data3 = pd.read_csv('data3.txt',skiprows=2,sep = r'\t')
data3.head(3).T

C:\Users\tjroc\AppData\Local\Temp\ipykernel_2924\350615365.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  data3 = pd.read_csv('data3.txt',skiprows=2,sep = r'\t')

                                                  0       1        2
Country                                     Finland  Norway  Denmark
Happiness score                               7.632   7.594    7.555
Whisker-high                                  7.695   7.657    7.623
Whisker-low                                   7.569    7.53    7.487
Dystopia (1.92) + residual                    2.595   2.383     2.37
Explained by: GDP per capita                  1.305   1.456    1.351
Explained by: Social support                  1.592   1.582     1.59
Explained by: Healthy life expectancy         0.874   0.861    0.868
Explained by: Freedom to make life choices    0.681   0.686    0.683
Explained by: Generosity                      0.192   0.286    0.284
Explained by: Perceptions of corruption       0.393    0.34    0.408

### Part e
Load `data4.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

**When I viewed the file I saw that it was delimited using a dollar sign and that there were no column names. So, I used the column names vector from above to set the column names, I indicated there was no header row, and I used sep = dollarsign to set the delimeter to dollarsign.**

In [52]:
data4 = pd.read_csv('data4.txt',header = None, names = column_names, sep = "$")
data4.head(3).T

                                                  0       1        2
Country                                     Finland  Norway  Denmark
Happiness score                               7.632   7.594    7.555
Whisker-high                                  7.695   7.657    7.623
Whisker-low                                   7.569    7.53    7.487
Dystopia (1.92) + residual                    2.595   2.383     2.37
Explained by: GDP per capita                  1.305   1.456    1.351
Explained by: Social support                  1.592   1.582     1.59
Explained by: Healthy life expectancy         0.874   0.861    0.868
Explained by: Freedom to make life choices    0.681   0.686    0.683
Explained by: Generosity                      0.192   0.286    0.284
Explained by: Perceptions of corruption       0.393    0.34    0.408

### Part f
Load `data5.csv`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

**This file loaded properly on its own by only specifying the file name.**

In [55]:
data5=pd.read_csv('data5.csv')
data5.head(3).T

                                                  0       1        2
Country                                     Finland  Norway  Denmark
Happiness score                               7.632   7.594    7.555
Whisker-high                                  7.695   7.657    7.623
Whisker-low                                   7.569    7.53    7.487
Dystopia (1.92) + residual                    2.595   2.383     2.37
Explained by: GDP per capita                  1.305   1.456    1.351
Explained by: Social support                  1.592   1.582     1.59
Explained by: Healthy life expectancy         0.874   0.861    0.868
Explained by: Freedom to make life choices    0.681   0.686    0.683
Explained by: Generosity                      0.192   0.286    0.284
Explained by: Perceptions of corruption       0.393    0.34    0.408

### Part g
Load `data6.dat`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (Note: for this question, your result won't look *exactly* like data_clean.csv, and that is OK.) [6 points]

**This file loaded properly using .read_csv as it is comma-delimited with no extra rows. My only parameter was the file name.**

In [62]:
data6=pd.read_csv('data6.dat')
data6.head(3).T

                                                  0       1        2
Country                                     Finland  Norway  Denmark
Happiness score                               7.632   7.594    7.555
Whisker-high                                  7.695   7.657    7.623
Whisker-low                                   7.569    7.53    7.487
Dystopia (1.92) + residual                    2.595   999.0     2.37
Explained by: GDP per capita                  999.0   999.0    1.351
Explained by: Social support                  999.0   1.582     1.59
Explained by: Healthy life expectancy         999.0   999.0    999.0
Explained by: Freedom to make life choices    0.681   0.686    0.683
Explained by: Generosity                      0.192   0.286    0.284
Explained by: Perceptions of corruption       0.393    0.34    0.408

### Part h
Load `data7.xlsx`, which is an Excel file. Keep only the sheet named “Data”. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

**I used read_excel to load this file, and the only additional parameter I passed it was the sheet_name, which identified which sheet in the excel file to load.**

In [64]:
data7=pd.read_excel('data7.xlsx',sheet_name = 'Data')
data7.head(3).T

                                                  0       1        2
Country                                     Finland  Norway  Denmark
Happiness score                               7.632   7.594    7.555
Whisker-high                                  7.695   7.657    7.623
Whisker-low                                   7.569    7.53    7.487
Dystopia (1.92) + residual                    2.595   2.383     2.37
Explained by: GDP per capita                  1.305   1.456    1.351
Explained by: Social support                  1.592   1.582     1.59
Explained by: Healthy life expectancy         0.874   0.861    0.868
Explained by: Freedom to make life choices    0.681   0.686    0.683
Explained by: Generosity                      0.192   0.286    0.284
Explained by: Perceptions of corruption       0.393    0.34    0.408

### Part i
Load `data8.dta`, which is a Stata 13 file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

**I used read_stata and it loaded properly with only the file parameter passed.**

In [70]:
data8=pd.read_stata('data8.dta')
data8.head(3).T

                                        0       1        2
country                           Finland  Norway  Denmark
happinessscore                      7.632   7.594    7.555
whiskerhigh                         7.695   7.657    7.623
whiskerlow                          7.569    7.53    7.487
dystopia192residual                 2.595   2.383     2.37
explainedbygdppercapita             1.305   1.456    1.351
explainedbysocialsupport            1.592   1.582     1.59
explainedbyhealthylifeexpectancy    0.874   0.861    0.868
explainedbyfreedomtomakelifechoi    0.681   0.686    0.683
explainedbygenerosity               0.192   0.286    0.284
explainedbyperceptionsofcorrupti    0.393    0.34    0.408

### Part j
Load `data9.sav`, which is an SPSS file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

**I used read_spss to load the file, and only needed to pass the file name parameter.**

In [68]:
data9=pd.read_spss('data9.sav')
data9.head(3).T

                   0       1        2
country      Finland  Norway  Denmark
happiness      7.632   7.594    7.555
whiskerhigh    7.695   7.657    7.623
whiskerlow     7.569    7.53    7.487
dystopia       2.595   2.383     2.37
gdpPC          1.305   1.456    1.351
socsupport     1.592   1.582     1.59
lifeexp        0.874   0.861    0.868
lifechoice     0.681   0.686    0.683
generous       0.192   0.286    0.284
corrupt        0.393    0.34    0.408

### Part k
Load `data10.xpt`, which is a SAS file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. 

(If some of the country names display as `b'Finland'`, don't worry about that.)

(But if you are still worrying about it ... issues like `b'Finland'` indicate a [character encoding](https://en.wikipedia.org/wiki/Character_encoding) issue, in which SAS uses a different encoding method than Python. In this case Python uses a default encoding called [UTF-8](https://en.wikipedia.org/wiki/UTF-8) and this SAS file has encoded characters using [Latin-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1). To get around this issue, add the `encoding='latin-1'` argument to your read method.) 

[4 points]

**I used read_sas with only the file and encoding parameters specified, and it loaded properly.**

In [71]:
data10 = pd.read_sas('data10.xpt',encoding = 'latin1')
data10.head(3).T

                0       1        2
COUNTRY   Finland  Norway  Denmark
HAPPINES    7.632   7.594    7.555
WHISKERH    7.695   7.657    7.623
WHISKERL    7.569    7.53    7.487
DYSTOPIA    2.595   2.383     2.37
EXPLAINE    1.305   1.456    1.351
EXPLAIN2    1.592   1.582     1.59
EXPLAIN3    0.874   0.861    0.868
EXPLAIN4    0.681   0.686    0.683
EXPLAIN5    0.192   0.286    0.284
EXPLAIN6    0.393    0.34    0.408

### Part l
Please load the `data11.txt` file, which is a fixed width file. The columns are defined as follows:

| Variable                                   | Width | Start | End |
|--------------------------------------------|-------|-------|-----|
| Country                                    | 24    | 1     | 24  |
| Happiness score                            | 5     | 25    | 29  |
| Whisker-high                               | 5     | 30    | 34  |
| Whisker-low                                | 5     | 35    | 39  |
| Dystopia (1.92) + residual                 | 5     | 40    | 44  |
| Explained by: GDP per capita               | 5     | 45    | 49  |
| Explained by: Social support               | 5     | 50    | 54  |
| Explained by: Healthy life expectancy      | 5     | 55    | 59  |
| Explained by: Freedom to make life choices | 5     | 60    | 64  |
| Explained by: Generosity                   | 5     | 65    | 69  |
| Explained by: Perceptions of corruption    | 5     | 70    | 74  |

Then save the this loaded data frame as a CSV file on your local machine. Be sure to use a unique filename so as not to overwrite any existing files. [10 points]

In [ ]:
data11=pd.read_fwf('data11.txt',widths = [24,5,5,5,5,5,5,5,5,5,5], names = column_names)
data11.head(3).T
#data11.to_csv('data11fixed.csv')

## Problem 2
This problem walks through how to wrangle some difficult real-world Excel data into Python. This problem is guided, but later in the semester you'll be asked more often to do work with less guidance. 

The file named "epa_data.xlsx" contains data on the reproduction and growth of nine different plant species, measured once in 2010 and once in 2011. The data were compiled from the [EPA's repository](https://catalog.data.gov/dataset/18-excel-spreadsheets-by-species-and-year-giving-reproduction-and-growth-data-one-excel-sp) on data.gov. I placed all of the data into a single file, where the different species/year combinations are placed in different sheets. The file also includes a sheet for herbicide treatment chemistry data, and one sheet for a ReadMe describing some of the columns in the growth data.

### Part a
If you load an Excel file with multiple sheets into Python using the `sheet_name=None` argument, then every sheet's data will be stored in one big Python dictionary. 

We will discuss dictionaries (and JSON formatted data) in depth in module 3. However, for this problem, there a few points to know about dictionaries:

* Dictionaries are similar to lists, except that they are denoted with curly braces {} instead of square braces [], and that entries in the dictionary are indexed by names instead of numeric positions.

* Entries in a dictionary are called values, and the names attached to the entries are called keys. Your output will set the former sheet names as the keys for each data table.

* To display one of the values, call the Python variable that contains the dictionary, and index it by the value's key. For example, if you save the data as `epadata`, then you can see the 2010 data for species CALE by typing `epadata['CALE 2010']`. 

Load all of the data, across all of the sheets, from this Excel file into Python. Then index to one of the values in the resulting dictionary to display one of the former sheets as a pandas dataframe. [8 points]

### Part b
To see all of the keys in the dictionary, use the `.keys()` method on the data dictionary you created in part a. If you do, you will notice that two keys are not like the others:

* `Solution Chemistry` contains different data: information about common pesticides instead of the growth and reproduction of a particular species of plant.

* `ReadMe` contains descriptions of some columns in the species-level data.

To delete a key and value from a dictionary, use the following syntax `del d[key]`, where `d` is the Python variable that contains the dictionary, and `key` is the name (quotes included) of the key attached to the value you want to remove from the dictionary. If you use this command, the dictionary is altered *in place*, meaning that there is no need to write `d=` before this command in order to make these edits to the dictionary permanent.

Delete the `Solution Chemistry` and `ReadMe` data from the dictionary. [8 points]

### Part c
Combining two data tables with the same columns but entirely different rows is called **appending** data. Our goal is to append all of the remaining data tables together, to create one large dataframe containing all plant species and both 2010 and 2011 data. 

It is only possible, however, to append data if both data tables have exactly the same column names. If a column in one table is not matched in the other table, the column will be populated with missing values for the rows that come from the second table. There are two reasons why columns might not match: the two tables might not contain the same features, or the two tables contain the same feature but named differently in each table. 

For example, in this case, some of the sheets have columns that others do not, such as biomass. Other features are present in every sheet, but with different names: year is sometimes spelled with a capital Y.

To deal with these issues, we will use a loop over the keys in the dictionary you edited in part b. Begin the loop by typing 
```
for df in d.keys():
```
where `d` is the name of your dictionary.

On the next line, indent (which indicates this line should be run within the loop). Then write
```
d[df].columns = d[df].columns.str.lower()
```
which will alter all column names across all of the dataframes to be lower-case.

In addition, some of the column names have extra spaces at the end, and that will make columns fail to match as well. To remove these spaces, add the following line to the loop:

```
d[df].columns = d[df].columns.str.strip()
```
which removes leading and trailing spaces from each column name. [10 points]

### Part d
Use the `pd.concat()` method to append all of the dataframes in your dictionary together. You can pass the entire dictionary to the first argument of `pd.concat()`. Specify `ignore_index=True`, which resets the row numbering instead of bringing in the old row numbers from the individual dataframes. [8 points]

### Part e
Many of the features that were brought into the appended dataframe were only present for one or a small number of the dataframes. Keep only the following features, which are present for most of the species:

In [37]:
cols_to_keep = ['year', 'species', 'site', 'plot', 'trt', 'treatment', 
                'pods', 'cover0', 'arsincover0', 'cover3', 'arsincover3', 
                'cover5', 'arsincover5']

Then save the resulting data in a separate CSV file. [8 points]